version: '3.8'

services:
  aggregator:
    build: ./src/aggregator
    networks:
      - management_network
    volumes:
      - ./artifacts/release:/logs
    ports:
      - "8443:8443"

  sensor:
    build: ./src/sensor
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - sensor_network
      - management_network
    depends_on:
      - aggregator

networks:
  sensor_network:
    internal: true
  management_network:
    driver: bridge